theme: jekyll-theme-minimal
relative_links:
  enabled: true
  collections: true
include:
  - FIRSTRUN.md
  - README.md
  - MEDIA.md
  - annotations.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - implemented_algorithms.md
  - datasets.md
title: [Velocity]
description: [Velocity by AI4U is a tool to manage the full life cycle of deep learning]
logo: assets/ForWhiteBackgroundsm.png

